Ahnblog/Ahnblog/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls', namespace='blog')),
] 

urlpatterns += static(settings.MEDIA_URL,
document_root=settings.MEDIA_ROOT)

Ahnblog/blog/urls.py
from django.conf.urls import include, url
from blog import views

urlpatterns = [
       url(r'^$',views.index,name="index"),
       url(r'^posts/$',views.post_list,name='post_list'),
       url(r'^posts/new/$', views.post_new, name='post_new'),
       url(r'^posts/(?P<pk>\d+)/$', views.post_detail,name='post_detail'), 
       url(r'^about-me/$', views.about_me, name='about_me'),
]

Ahnblog/blog/models.py
from django.db import models
from django.conf import settings
# Create your models here.

class Post(models.Model):
	title=models.CharField(max_length=100, help_text='제목은 100글자')
	author=models.ForeignKey(settings.AUTH_USER_MODEL)
	content=models.TextField()
	photo=models.ImageField(blank=True, upload_to="uploads/%Y/%m/%d")
	create_at=models.DateTimeField(auto_now_add=True)
	update_at=models.DateTimeField(auto_now=True)

Ahnblog/blog/forms.py
from django import forms
from blog.models import Post

class PostForm(forms.ModelForm):
	class Meta:
		model = Post
		fields = (
			'title',
			'photo',
			'content',
			)

Ahnblog/blog/views.py
from django.shortcuts import render, redirect
from blog.models import Post
from blog.forms import PostForm
from django.contrib.auth.decorators import login_required

def index(request):
	return render(request, 'blog/index.html')

def post_list(request):
	posts = Post.objects.all()
	return render(request, 'blog/post_list.html', {
		'posts':posts,
		})

def post_detail(request, pk):
	post = Post.objects.get(pk=pk)
	return render(request, 'blog/post_detail.html', {
		'post':post,
		})

@login_required
def post_new(request): 
	if request.method == "POST":
		form=PostForm(request.POST, request.FILES)
		if form.is_valid():
			form = form.save(commit=False)
			form.author = request.user
			form.save()
			return redirect("blog:post_list")
	else:
		post_form = PostForm()
		return render(request, 'blog/post_form.html', {'post_form':post_form})

def about_me(request):
	return render(request, 'blog/about_me.html')
# Create your views here.

Ahnblog/Ahnblog/templates/base.html
{% load bootstrap3 %}
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no" />
<title>JooEun</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" />
<style>
body {
    padding-top: 60px;
}
html {
  position: relative;
  min-height: 100%;
}
body {
  margin-bottom: 60px;
}
.footer {
  position: absolute;
  bottom: 0;
  width: 100%;
  height: 60px;
  background-color: #f5f5f5;
}
</style>
</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url "blog:index"%}">Home</a>
            <a class="navbar-brand" href="{% url "blog:about_me" %}">About me</a>
            <a class="navbar-brand" href="{% url "blog:post_list" %}">Post</a>
        </div>
    </div>
</div>
{% block content %}

{% endblock %}

<div class="footer">
    <div class="container">
        <p class="text-muted">Place sticky footer content here.</p>
    </div>
</div>

</body>
</html>

Ahnblog/blog/templates/blog/about_me.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}

<img src="{% static 'img/Ahn.jpg' %}">


{% endblock %}

Ahnblog/blog/templates/blog/index.html
{% extends "base.html" %}

{% block content %}

<div class="container">
    <div class="jumbotron">
        <h1>JooEunAhn Blog</h1>
        <p>Hi Hi, </p>
    </div>
</div>


{% endblock %}

Ahnblog/blog/templates/blog/post_detail.html
{% extends 'base.html' %}
{% load staticfiles %}


{% block content %}
{{post.title}}
{{post.photo.url}}
<img src='{{post.photo.url}}'>
{{post.content}}
{% endblock %}

Ahnblog/blog/templates/blog/post_form.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block content %}
<form action="" method = "post" enctype="multipart/form-data">
{% csrf_token %}
{% bootstrap_form post_form %}
<input type="submit" value="등록">
</form>
{% endblock %}

Ahnblog/blog/templates/blog/post_list.html
{% extends "base.html" %}
{% block content %}
{% for post in posts %}
<a href = "{% url 'blog:post_detail' post.pk %}">
{{post.title}}</a>
{% endfor %}

<a href="{% url 'blog:post_new' %}">새 글쓰기</a>
{% endblock %}